version: 2.1
jobs:
  test:
    docker:
      - image: cypress/base:12.1.0
    steps:
      - checkout
      - run:
          name: Install deps
          command: npm install
      - run:
          name: Run tests
          command: npm run test:component
workflows:
  run-tests:
    jobs:
      - test:
          context: env-vars