version: 2.1
orbs:
  node: circleci/node@5.1
jobs:
  install-node-example:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: '18.13.0'
      - run: node --version
  test:
    docker:
      - image: cypress/base:16.13.0
    steps:
      - checkout
      - run:
          name: Install deps
          command: npm install
      - run:
          name: Run tests
          no_output_timeout: 30m
          command: npm run test:component
workflows:
  run-tests:
    jobs:
      - install-node-example
      - test:
          requires:
            - install-node-example